[package]
name = "physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "0.31.4"
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"
